//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gds.LiteConstruct.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gds.LiteConstruct.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter for type &apos;{0}&apos; has been already registered.
        /// </summary>
        internal static string AdapterForType0HasBeenAlreadyRegistered {
            get {
                return ResourceManager.GetString("AdapterForType0HasBeenAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter for type &apos;{0}&apos; has not been registered.
        /// </summary>
        internal static string AdapterForType0HasNotBeenRegistered {
            get {
                return ResourceManager.GetString("AdapterForType0HasNotBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add {0}.
        ///
        ///This {0} exists in the list of related {0}s..
        /// </summary>
        internal static string CannotAddExistingRelationFormat {
            get {
                return ResourceManager.GetString("CannotAddExistingRelationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add {0}.
        ///
        ///Current {0} has the same language..
        /// </summary>
        internal static string CannotAddItemCurrenyHasThisLanguageFormat {
            get {
                return ResourceManager.GetString("CannotAddItemCurrenyHasThisLanguageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add {0}.
        ///
        ///There is a {0} in a group with the same language..
        /// </summary>
        internal static string CannotAddItemGroupHasThisLanguageFormat {
            get {
                return ResourceManager.GetString("CannotAddItemGroupHasThisLanguageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add {0}.
        ///
        ///You can not set relation to the same {0}..
        /// </summary>
        internal static string CannotAddSameRelationFormat {
            get {
                return ResourceManager.GetString("CannotAddSameRelationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is already set.
        /// </summary>
        internal static string CommandIsAlreadySet {
            get {
                return ResourceManager.GetString("CommandIsAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to properties.
        /// </summary>
        internal static string EditFormManagerTitle {
            get {
                return ResourceManager.GetString("EditFormManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail not valid..
        /// </summary>
        internal static string EMailNotValid {
            get {
                return ResourceManager.GetString("EMailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item type does not has a property with a specified attribute name.
        /// </summary>
        internal static string FailedToFindRelatedProperty {
            get {
                return ResourceManager.GetString("FailedToFindRelatedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field can&apos;t be empty..
        /// </summary>
        internal static string FieldCanTBeEmpty {
            get {
                return ResourceManager.GetString("FieldCanTBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoker has incorrect type.
        /// </summary>
        internal static string InvokerHasIncorrectType {
            get {
                return ResourceManager.GetString("InvokerHasIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invoker is not registered.
        /// </summary>
        internal static string InvokerIsNotRegistered {
            get {
                return ResourceManager.GetString("InvokerIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemInProgress can be accessed from thread where WorkItem was created.
        /// </summary>
        internal static string ItemInProgressCanBeAccessedFromThreadWhereWorkItemWasCreated {
            get {
                return ResourceManager.GetString("ItemInProgressCanBeAccessedFromThreadWhereWorkItemWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item is already added to workitem.
        /// </summary>
        internal static string ItemIsAlreadyAddedToWorkitem {
            get {
                return ResourceManager.GetString("ItemIsAlreadyAddedToWorkitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item is not added to workitem.
        /// </summary>
        internal static string ItemIsNotAddedToWorkitem {
            get {
                return ResourceManager.GetString("ItemIsNotAddedToWorkitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty.
        /// </summary>
        internal static string NameCanTBeEmpty {
            get {
                return ResourceManager.GetString("NameCanTBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewItemTitle {
            get {
                return ResourceManager.GetString("NewItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can contain only alphanumeric symbols(witout spaces).
        /// </summary>
        internal static string OnlyAlphanumericSymbols {
            get {
                return ResourceManager.GetString("OnlyAlphanumericSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of object returned by related property does not equals type specified in related binding source.
        /// </summary>
        internal static string RelatedPropertyIncorrectResult {
            get {
                return ResourceManager.GetString("RelatedPropertyIncorrectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property with a specified attribute name has another type than in specified binding source.
        /// </summary>
        internal static string RelatedPropertyTypeIsIncorrect {
            get {
                return ResourceManager.GetString("RelatedPropertyTypeIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TitleInformation {
            get {
                return ResourceManager.GetString("TitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string TitleQuestion {
            get {
                return ResourceManager.GetString("TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cannot be completed..
        /// </summary>
        internal static string ValidationErrorTitle {
            get {
                return ResourceManager.GetString("ValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workitem can be removed only from parent workitem.
        /// </summary>
        internal static string WorkitemCanBeRemovedOnlyFromParentWorkitem {
            get {
                return ResourceManager.GetString("WorkitemCanBeRemovedOnlyFromParentWorkitem", resourceCulture);
            }
        }
    }
}
